sudo: false
language: python
python:
- '2.6'
- '2.7'
install:
- pip install -r requirements.txt
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
script:
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then unit2 discover -v -t tests/ -p "*_test.py"; else python -m unittest discover -s tests/ -p "*_test.py"; fi
